language: python

python:
  - "2.7"

env:
  - TOXENV=py34-trunk,py27-trunk
  - TOXENV=py34-1.7,py33-1.7,py32-1.7,py27-1.7
  - TOXENV=py33-1.6,py32-1.6,py27-1.6,py26-1.6
  - TOXENV=py33-1.5,py32-1.5,py27-1.5,py26-1.5
  - TOXENV=py27-1.4,py26-1.4
  - TOXENV=flake8
  - TOXENV=coverage
  - TOXENV=docs

install:
  - pip install tox

script:
  - tox

matrix:
  allow_failures:
    - env: TOXENV=py34-trunk,py27-trunk
